"""create users table

Revision ID: 7f115501899b
Revises: 0001_create_users
Create Date: 2026-01-16 10:58:18.381497

"""

from __future__ import annotations

revision = "7f115501899b"
down_revision = "0001_create_users"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
